### ISSUE TITLE
RyoamicLights 0.2.10 config not being overwritten properly

### ISSUE THREAD

**Issue by NovaViper** [ThinkingStudios/RyoamicLights#41]
**Describe the bug**
So after updating the initial crashing that was present in #38 is gone, but only after the first launch (and me not touching the configuration at all). As soon as I open the in-game config menu for the mod; it creates a duplicate [light_sources] entry; which is exactly the bug that's causing #40 for fabric users (and in my case, also affects NeoForge!).

**To Reproduce**
1. Launch Minecraft (make sure that the config for RyoamicLights doesn't exist first, the normal config with just the light_sources entry is created)
1. Go to 'Mods' in the game menu
2. Click on 'RyoamicLights' and open its mod configuration menu (editing any values is not necessary)
4. Close the game immediately
5. Relaunch the game
6. Crash occurs

**Expected behavior**
Opening the mod's configuration menu should not result in a duplicate light_sources entry, it should completely clear the file first and then add in the new configurations

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux 6.9.9-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240719.a069165
 - Minecraft 1.21
 - NeoForge version 0.2.10+mc1.21.1
 - Mods [client-1.21-20240613.152323-srg.jar, RyoamicLights-neoforge-0.2.10+mc1.21.1.jar,ObsidianUI-neoforge-0.2.7+mc1.21.jar,neoforge-21.0.148-universal.jar]
 - Version 0.2.10
 - Branch [mc1.21.x]

**Additional context**

**Comment by TexBlock** [comment]
fixed in 0.2.11

**Comment by leon0399** [comment]
Btw it still crashes on `0.2.11`, until I deleted config file

**Comment by TexBlock** [comment]
> Btw it still crashes on 0.2.11, until I deleted config file

You need to delete the old configuration first
